### ISSUE TITLE
Documentation (of clustering algorithms)

### ISSUE THREAD

**Issue by ckaldemeyer** [FZJ-IEK3-VSA/tsam#1]
Hi there,

thanks for creating this package and I am already looking forward to the webinar (on Netzwerk Energysystemanalyse) tomorrow!

As we would like to use the package for a research project, I am very interested in the documentation. Do you already have a pre-print version of your paper or something that can be used?

Or did you implement the clustering (I am interested in hierachical and k-means) according to the following papers?

* http://www.sciencedirect.com/science/article/pii/S0360544216308556
* http://ieeexplore.ieee.org/document/6729088/

Then I could have a look at these and already cite with you DOI..

Thanks in advance!
Cord

**Comment by ckaldemeyer** [comment]
To make it a bit clearer: The first paper uses Ward's hierachical clustering on demand + VRE and the second k-means with  Euclidean distance on demand only.

**Comment by l-kotzur** [comment]
Hey Cord,

the hierarchical aggregation is using the AgglomerativeClustering class from sklearn with the 'Ward' algorithm as in the paper you mentioned. 

The k-mean uses as you said also the Euclidean distance.

The k-medoid is formulated as an exact MILP with pyomo, as introduced in this paper:
http://www.sciencedirect.com/science/article/pii/S037877881100329X?via%3Dihub

I will check the options of publishing a pre-print.

Best
Leander

**Comment by ckaldemeyer** [comment]
> Hey Cord,
> 
> the hierarchical aggregation is using the AgglomerativeClustering class from sklearn with the 'Ward' algorithm as in the paper you mentioned.
> 
> The k-mean uses as you said also the Euclidean distance.
> 
> The k-medoid is formulated as an exact MILP with pyomo, as introduced in this paper:
> http://www.sciencedirect.com/science/article/pii/S037877881100329X?via%3Dihub
> 
> I will check the options of publishing a pre-print.
> 
> Best
> Leander

Thanks!
