### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ulfmueller** [FZJ-IEK3-VSA/tsam#13]
Are there any plans for a new release?
And would you consider to release tsam also at [pypi](https://pypi.org/)?

Since we use tsam now in our apps it would be nice to 
a) get the recent changes within in a new released version
b) being able to simply install that version from pypi

**Comment by l-kotzur** [comment]
On a short term perspective, there wont be any new release. But we are strategically working on the subject, especially focusing on alternative aggregation algorithms. Or do you have other features in mind?

Regarding pypi, I think it would be helpfull. Nevertheless, I need to become acquainted to it first.

**Comment by ulfmueller** [comment]
Right now I have no new concrete features in mind besides the slight adjustments which are already in the master but not part of a recent release. I simply would like to use these adjustments and being able to install a version via pip from pypi. How about you or I (as you like) create a very minor release 0.9.6 including the recent changes (such as the [datetimeindex](https://github.com/FZJ-IEK3-VSA/tsam/pull/12)) and then I could upload that version to pypi and write a little wiki checklist which explains the 'how to release on pypi'?
If you rather want to do it yourself, [here](https://github.com/openego/eTraGo/wiki/How-to-release) we roughly explain what to do for publishing a release on pypi (last bullit point of 'Day of release'). I could also try to explain it to you, if you want...

**Comment by l-kotzur** [comment]
I just tried it out and it went well! You can now install tsam via
`pip install tsam`
Thanks againg for pointing to the topic. I hope helps you!

Cheers
Leander

**Comment by ulfmueller** [comment]
Thanks a lot for effort! This will help us!
