### ISSUE TITLE
Allow to choose solvers from SolverFactory

### ISSUE THREAD

**Issue by ckaldemeyer** [FZJ-IEK3-VSA/tsam#14]
I have used `tsam` again for a small project and therefore installed the latest version from pypi.
Compared to my experiences with the initial version it took really long to cluster the data using all available methods. Then, I noticed that the standard solver has changed to `glpk` and before probably had been set to `gurobi`.

Unfortunately, I could not find an option to change this behaviour as the [call](https://github.com/FZJ-IEK3-VSA/tsam/blob/master/tsam/timeseriesaggregation.py#L141) for the medoids clustering uses the default value within the utils package/subfolder.

Wouldn't it make sense to provide this as an argument along with all other options such as cluster methods, etc.?

If you agree, I could also provide a quick pull request!

Cheers
Cord

**Comment by l-kotzur** [comment]
If you have a solution for this, I am open to integrate it!

**Comment by ckaldemeyer** [comment]
> If you have a solution for this, I am open to integrate it!

https://github.com/FZJ-IEK3-VSA/tsam/pulls

**Comment by ckaldemeyer** [comment]
Do you already know when you will provide the next release as mentioned in https://github.com/FZJ-IEK3-VSA/tsam/pull/15 ?

**Comment by l-kotzur** [comment]
Sorry for the delay, I was lost in finishing my thesis. 

I hesitated because it is version 1.0.0. Anyway, now it is out there and also uploaded to pip.
