### ISSUE TITLE
Data Normalization

### ISSUE THREAD

**Issue by ckaldemeyer** [FZJ-IEK3-VSA/tsam#2]
Hi again,

I have just looked at the example in which the input data has not been normalized: https://github.com/FZJ-IEK3-VSA/tsam/blob/master/example/aggregation_example.ipynb

If I have let's say 3 time series and (one normalized and two regular ones), is it mandatory to have all of them normalized in order to have the algorithm working correctly?

I am guessing, yes..

Best
Cord

**Comment by l-kotzur** [comment]
Hi Cord,

the normalization procedure is integrated into the aggregation procedure. All time series get scaled to a [0,1]-Scale before clustering and then scaled back afterwards. 

There is also the possibility to weight the time series, which is just changing the scale of the series such that their shapes get evaluated more or less in the distance measure between the candidate periods.

I hope that helped you.

Best
Leander

**Comment by ckaldemeyer** [comment]
> Hi Cord,
> 
> the normalization procedure is integrated into the aggregation procedure. All time series get scaled to a [0,1]-Scale before clustering and then scaled back afterwards.
> 
> There is also the possibility to weight the time series, which is just changing the scale of the series such that their shapes get evaluated more or less in the distance measure between the candidate periods.
> 
> I hope that helped you.
> 
> Best
> Leander

Yes :+1:

Thanks!
