### ISSUE TITLE
Picking more than 24 hours (4 type weeks)

### ISSUE THREAD

**Issue by ckaldemeyer** [FZJ-IEK3-VSA/tsam#3]
I am doing some tests and everything seems to work well with less than 24 hours.

But if I change the call from let's say:

	aggregation = tsam.TimeSeriesAggregation(normalized, noTypicalPeriods=7,
		                                 hoursPerPeriod=24,
		                                 clusterMethod='hierarchical')

to (trying to pick 4 type weeks per year):

	aggregation = tsam.TimeSeriesAggregation(normalized, noTypicalPeriods=4,
		                                 hoursPerPeriod=24*7,
		                                 clusterMethod='hierarchical')

I get an error:

	Traceback (most recent call last):
	  File "cluster.py", line 34, in <module>
	    typPeriods = aggregation.createTypicalPeriods()
	  File "/home/cord/Programmierung/tsam/tsam/timeseriesaggregation.py", line 793, in createTypicalPeriods
	    self.clusterPeriodNoOccur[self.clusterOrder[-1]] -= (1 - float(len(self.timeSeries) % self.timeStepsPerPeriod)/self.timeStepsPerPeriod)
	AttributeError: 'TimeSeriesAggregation' object has no attribute 'clusterPeriodNoOccur'

I have observed that it pops up when I change the value of `hoursPerPeriod` to more than 24 hours.

Can anyone help?

Best
Cord

**Comment by ckaldemeyer** [comment]
If you want, I can also prepare a gist with the script/data to reproduce the error..

**Comment by l-kotzur** [comment]
Hey Cord,

it should work now.

Thanks for your feedback!

Best
Leander

**Comment by ckaldemeyer** [comment]
> Hey Cord,
> 
> it should work now.
> 
> Thanks for your feedback!
> 
> Best
> Leander

Thanks for fixing!
