### ISSUE TITLE
Add automatic documentation with Sphinx

### ISSUE THREAD

**Issue by larsschellhas** [FZJ-IEK3-VSA/tsam#41]
Python allows for automatic extraction of docstrings, methods, classes, etc. and automatically creating more readable documentations in HTML or PDF format. For example, the Python documentation itself and the documentation of Pyomo are created this way.

The package for this is called [Sphinx](http://www.sphinx-doc.org/en/master/) and can be automatically run by CI runners (e.g. [Travis CI](https://travis-ci.org/) [free for open-source projects]). The documentation can also be hosted on [ReadTheDocs.org](https://readthedocs.org/) for free and make the package even more accessible.

**Comment by l-kotzur** [comment]
Solved :) https://tsam.readthedocs.io/en/latest/

**Comment by larsschellhas** [comment]
Very nice! 👍
