### ISSUE TITLE
Aggregated peak 

### ISSUE THREAD

**Issue by samuelduchesne** [FZJ-IEK3-VSA/tsam#45]
Hi guys (@l-kotzur @maximilian-hoffmann),
I was wondering if there was a way to create an additional typical period (extremePeriodMethod) for the **aggregated peak** of a collection of profiles (concurrent peak) and not just the profile which contains the peak.

Great to see the activity on this package. It is super useful!

Best,

Sam

**Comment by l-kotzur** [comment]
@maximilian-hoffmann Would this be possible?

**Comment by maximilian-hoffmann** [comment]
Hey Sam,
as I understand your question, you want to keep the extreme values for, let's say, the day with the maximum cumulative demand over all regions. At the moment, tsam does not disinguish between different attribute types and the same attribute at different locations. Therefore, this is not a built-in function. However, here are two workarounds that lead to diffenrent results but might be exactly what you want:

1. Simply append a time series that is the sum of the other attributes to your dataframe and define an extreme period method for that attribute.
2. Run the clustering process once and extract the clusterOrder attribute. Then, manipulate the cluster order to your needs e.g. by giving some values a new number, e.g. you cluster 10 days to three typical periods and get the order 1122133321. Now you want the seventh value to be unique. Accordingly, change the order to 1122133421. Then run tsam again and pass the "predefinedClusterOrder". Then, the clusters are rebuilt and put the seventh value into an own cluster.

I hope that helps. :smile:
Kind regards,
Max
