### ISSUE TITLE
Accuracy indicators: Which normalization type?

### ISSUE THREAD

**Issue by ckaldemeyer** [FZJ-IEK3-VSA/tsam#46]
Hi there,

I have tried your new method to calculate indicators: `indicators = aggregation.accuracyIndicators()`

As both the RMSE and MAE are absolute error measures in their original form, I assume that the obtained low values are calculated based on the normalized time series and consequently relative i.e. the NRMSE and NMAE (see https://en.wikipedia.org/wiki/Root-mean-square_deviation for an example). From your code base, I see that you just import the calculation from `scikit.learn`.

This brings me to my question(s):

Am I right with my assumption?
And if yes, which normalization type did you choose for the time series?
Is is `value(t)/max(values)-min(values)` or `value(t)/max(values)`?
And the indicator itself is calculated for each column itself, right?

Thanks in advance for your help!

Cheers,
Cord

**Comment by l-kotzur** [comment]
@ckaldemeyer Hey Cord,

I should turn on the Email notifications. For the second question: I can say that we use the normalization between 0 and 1, `(value(t)-min(values))/ (max(values)-min(values))`. The other questions, my colleague @maximilian-hoffmann can answeer better.

Best
Leander

**Comment by maximilian-hoffmann** [comment]
Hey Cord,
you are right with your assumption(s)!

- the accuracy indicators are calcuated based attributewise based on the normalized values, i.e. each attribute is taken separately and compared to the corresponding original time series of that attribute. If you want to calcluate the RMSE of the clustering, choose sqrt(sum_over_all_attributes(RMSE_attribute^2)).
- the normalization is `(value(t)-min(values))/ (max(values)-min(values))`

Kind regards,
Max :smile:

**Comment by ckaldemeyer** [comment]
Thanks for your explanation!

Just as an idea: Would it make sense to rename the indicators and respective dataframe columns to `NRMSE, NRMSE_duration and NMAE` and add the information on the normalized calculation within the examples to make things a bit clearer?

Thanks anyway! I am fine now and you can close the issue if you want ;)

**Comment by maximilian-hoffmann** [comment]
Hey Cord,
thanks for your answer! We'll implement your proposal in th enext tsam release, which is by the way focusing on a clearer structure of tsam. :smile:
Kind regards,
Max
