### ISSUE TITLE
Mapping: Period<->Representative period

### ISSUE THREAD

**Issue by ckaldemeyer** [FZJ-IEK3-VSA/tsam#5]
Hi again,

how can I obtain information about which periods have been selected e.g. weeks 2, 15, 35, and 46 are the chosen ones with the corresponding weighting factors (if any)?

Sorry for asking so many questions at once..

Best
Cord

**Comment by ckaldemeyer** [comment]
And does the algorithm choose the same time slice for all the series e.g. a week with linked demand, wind and pv values or different weeks within each series e.g. week 1 and 43 for demand, 4 and 9 for wind and so on?

**Comment by ckaldemeyer** [comment]
I think the first is the case, isn't it?

**Comment by ckaldemeyer** [comment]
I found:

    # The order of the cluster Periods related to the original profile.
    tsam.TimeSeriesAggregation.clusterOrder

in the code.

I guess this should do it!

**Comment by ckaldemeyer** [comment]
It works now. Thanks anyway!

Just an idea: would it make sense to store the chosen/representing cluster period in the predicted data?

Then, all information is combined and with a datetimeindex one could also group and analyse which clusters have been chosen for certain positions, etc.

You can close this issue anyway!

**Comment by ckaldemeyer** [comment]
I have found the weights in the attribute `clusterPeriodNoOccur`so it works now. Maybe some general stats would be nice

**Comment by l-kotzur** [comment]
Do you have any ideas how to improve the useability of the mapping information in the code?

**Comment by ckaldemeyer** [comment]
> I have found the weights in the attribute clusterPeriodNoOccurso it works now. Maybe some general stats would be nice

Actually that only solved my problem partly and I still need to know which periods of the original time series have been chosen to represent the respective clusters.

My actual idea would be to go with pandas (like JOIN in SQL) and compare where the original an predicted data equals. The equal parts in the original data should be the selected periods, right?

> Do you have any ideas how to improve the useability of the mapping information in the code?

You mean generally like a reporting file?

The snipped I have is quite generic (I guess) and we might discuss along the code (pull request?) if parts could be integrated. But it's not something special so don't expect too much..

**Comment by l-kotzur** [comment]
> Actually that only solved my problem partly and I still need to know which periods of the original time series have been chosen to represent the respective clusters.

This would be possible, but only for k-medoid and hierarchical clustering. Therefore an easy solution could be possible. Wherefore do you need the information?

> You mean generally like a reporting file?

Yes, or some more data which gets directly returned after the aggregation. Atm the mapping information is hidden in in class attributes and you have to search in the source code to find these.

**Comment by ckaldemeyer** [comment]
> Actually that only solved my problem partly and I still need to know which periods of the original time series have been chosen to represent the respective clusters.
> This would be possible, but only for k-medoid and hierarchical clustering. Therefore an easy solution could be possible. Wherefore do you need the information?

We have a stochastic optimization and some metrics are generated via statistical models. For these models we need to know from which periods we have to pick the data from.

I have checked my comparison approach which maps the original and predicted data (check for equal values of one parameter e.g. Demand == Demand_predicted) and for both hierarchical and k-means not consecutive periods can be found.

Am I missing something? But the extracted type periods should be found 1:1 in the original file for hierarchical/k-means clustering, shouldn't they?

Could you tell me how you would to it?

> You mean generally like a reporting file?
>> Yes, or some more data which gets directly returned after the aggregation. Atm the mapping information is hidden in in class attributes and you have to search in the source code to find these.

Yes, that's where I found it.

For me, in the first stage 3 things are interesting:

1. The number of occurances of each cluster e.g. a 2D structure with the following columns: cluster, no_of_occurances
2. The cluster order for the representation of the original series e.g. a 2D structure with the following columns: cluster_representation_of_original_profile (holds profile numbers), [from_hour_orig, to_hour_orig]
3. The positions of the clusters in the original series (k-means, hierarchical only) which refers to my actual question

I think 1. and 2. could be written to CSV (that's how I do it) and be realized within a single method or via a "verbose flag" as I guess it's an information that's needed quite often.

**Comment by ckaldemeyer** [comment]
> I think 1. and 2. could be written to CSV (that's how I do it) and be realized within a single method or via a "verbose flag" as I guess it's an information that's needed quite often.

Another option would be to use XLS and different spreadsheets but I think pandas with XLS is not bulletproof in terms of different operating systems. So CSV is probably the safest option.

**Comment by ckaldemeyer** [comment]
From a DataFrame..

**Comment by ckaldemeyer** [comment]
> I have checked my comparison approach which maps the original and predicted data (check for equal values of one parameter e.g. Demand == Demand_predicted) and for both hierarchical and k-means no consecutive periods can be found.
> 
> Am I missing something? But the extracted type periods should be found 1:1 in the original file for hierarchical/k-means clustering, shouldn't they?
> 
> Could you tell me how you would to it?

I am still wondering why this is not working. Shouldn't the selected periods for the clusters match the original?

**Comment by ckaldemeyer** [comment]
Shouldn't it be just `clusterCenters` from `sklearn` within the function `aggregatePeriods` for the default case that could be provided as an attribute of `TimeSeriesAggregation`?

Nevertheless, normally the "matching approach" of predicted to original data should work, right?

**Comment by simnh** [comment]
Hi, I was wondering if this is already resolved? I would like to extract datetime information of the cluster days. How can I do this?

**Comment by ckaldemeyer** [comment]
> Shouldn't it be just clusterCenters from sklearn within the function aggregatePeriods for the default case that could be provided as an attribute of TimeSeriesAggregation?
> 
> Nevertheless, normally the "matching approach" of predicted to original data should work, right?

@l-kotzur: I have tested the matching approach and it worked. But providing this option automatically would be great!

**Comment by l-kotzur** [comment]
I have hesitated to implement it, since a direct matching of typical periods to the original periods just applies for medoid or hierarchical based clustering. and this only of the typical periods are not scaled (parameter: rescaleClusterPeriods). k-means generates periods which are average days of the overall cluster and do not occure in the original time frame. Or am I understanding you wrong what you want to have?

If you want to know which original period belongs to which cluster: 
'TimeSeriesAggregation.clusterOrder' gives order of typical period indices representing the original time series. 
'TimeSeriesAggregation.clusterPeriodNoOccur' gives the derived value, how many origianl periods each typical period represents.

Perhaps I should clarify this in the Readme or example.

**Comment by ckaldemeyer** [comment]
> I have hesitated to implement it, since a direct matching of typical periods to the original periods just applies for medoid or hierarchical based clustering, and this only in case that the typical periods are not scaled (parameter: rescaleClusterPeriods). k-means generates periods which are average periods of the overall cluster and do not occure in the original time frame. Or am I understanding wrong what you need?

This is what I needed (for medoids and hierarchical clustering) and I think what @simnh needs if I understood him right. But I understand your hesitation due to the k-means problem.

> If you want to know which original period belongs to which cluster:
> 'TimeSeriesAggregation.clusterOrder' gives the order of typical period indices representing the original time series.

Maybe these indices could be used to be written next to the datetimeindex of the original data so that one does not have to search/count. Would this be an approach!?

> 'TimeSeriesAggregation.clusterPeriodNoOccur' gives the derived value, how many origianl periods each typical period represents.
> Perhaps I should clarify this in the Readme or example.

This would be great. Anyhow, thanks for your explanation!

**Comment by l-kotzur** [comment]
> This is what I needed (for medoids and hierarchical clustering) and I think what @simnh needs if I understood him right. But I understand your hesitation due to the k-means problem.

I could implement it with @property decorator which throws an error, if a cluster method has been chosen which throws an error.

> Maybe these indices could be used to be written next to the datetimeindex of the original data so that one does not have to search/count. Would this be an approach!?

'TimeSeriesAggregation.predictOriginalData()' is basically doing this, just not giving the indices. It can be easily extended.

**Comment by ckaldemeyer** [comment]
> This is what I needed (for medoids and hierarchical clustering) and I think what @simnh needs if I understood him right. But I understand your hesitation due to the k-means problem.
> 
> I could implement it with @property decorator which throws an error, if a cluster method has been chosen which throws an error.
> 
>     Maybe these indices could be used to be written next to the datetimeindex of the original data so that one does not have to search/count. Would this be an approach!?
> 
> 'TimeSeriesAggregation.predictOriginalData()' is basically doing this, just not giving the indices. It can be easily extended.
> 
> I will try to implement both and keep you up to date.

Thanks. From my point of view the second option would be absolutely sufficient as it covers all cases and needs not special handling. But it is your package ;)

**Comment by simnh** [comment]
Thanks for clarifying! As I only used hierarchical clustering I kind of forgot  that for some methods there exists no 'real' days anymore after clustering. As I like to use the full functionality (incl. k-means) I will have to find another way to deal with this problem...

Should this one be  closed then?

**Comment by ckaldemeyer** [comment]
> Thanks for clarifying! As I only used hierarchical clustering I kind of forgot that for some methods there exists no 'real' days anymore after clustering. As I like to use the full functionality (incl. k-means) I will have to find another way to deal with this problem...
> 
> Should this one be closed then?

I think the proposed solution that writes the predicted series along with the indices solves this problem as you at least have a mapping even if the periods for k-mean cannot match due to the underlying method.

So from my point of view there are no other solutions to deal with this functionality -including the k-means method- than one of @l-kotzurs solutions (property or writing/holding the mapping).

**Comment by ckaldemeyer** [comment]
> Thanks for clarifying! As I only used hierarchical clustering I kind of forgot that for some methods there exists no 'real' days anymore after clustering.

With the "mapping solution" you still have the mapping "original -> representation (not exactly in original" for k-means if I understand it right and this is all that can be provided.

**Comment by l-kotzur** [comment]
> With the "mapping solution" you still have the mapping "original -> representation (not exactly in original)" for k-means if I understand it right and this is all that can be provided.

Yes! I will implement it and update the Readme and then close the issue.

**Comment by ckaldemeyer** [comment]
> With the "mapping solution" you still have the mapping "original -> representation (not exactly in original)" for k-means if I understand it right and this is all that can be provided.
> 
> Yes! I will implement it and update the Readme and then close the issue.

Thanks a lot!

**Comment by l-kotzur** [comment]
I added a second example in the latest develop version which introduces also the "indexMatching" function. It shows what original time index is represented by which aggregated period index. We will merge it soon into the master.

Further, the other properties are shortly introduced which can be used in the systen optimization.

I hope this helps you!

Cheers
Leander

**Comment by ckaldemeyer** [comment]
> I added a second example in the latest develop branch which introduces also the "indexMatching" function. It shows what original time index is represented by which aggregated period index. We will merge it soon into the master.
> 
> Further, other properties are shortly introduced which can be used in the systen optimization.
> 
> I hope this helps you!
> 
> Cheers
> Leander

Thanks! I'll check it out when I find time ;)

**Comment by ckaldemeyer** [comment]
> I added a second example in the latest develop branch which introduces also the "indexMatching" function. It shows what original time index is represented by which aggregated period index. We will merge it soon into the master.
> 
> Further, other properties are shortly introduced which can be used in the systen optimization.
> 
> I hope this helps you!
> 
> Cheers
> Leander

I just came across this within another context and originally there were two things discussed here from my opinion:

1. The mapping which period of the original is represented by which cluster (solved) -> 1:n relation
2. The information where a cluster is chosen from in the original -> 1:1 relation

Except for k-mean clustering, the second information can be obtained by comparing columns of the original time series with the one that consists of the representative periods. But this only works then clusters are not rescaled. How can I obtain this information in the case of rescaled clusters as well?

@l-kotzur : Do you already have a solution for this which I haven't seen?

Cheers
Cord
