### ISSUE TITLE
Problem with "predictOriginalData" and "weightDict"

### ISSUE THREAD

**Issue by sbruche** [FZJ-IEK3-VSA/tsam#51]
Sorry, it’s me again today.
I have another and a rather important issue. 
It seems like the predicted time series is not calculated correctly when a weighting value is applied for that series. Hence, also the accuracy indicators are wrong. 
The problem is somehow related to the "inverse_transform" method of the MinMaxScaler. Probably that’s a good spot to start searching. 
For validation, please consider the following minimal example. Everything is fine with a weighting value of 1. If selected differently – see yourself...

```python
import pandas as pd
from tsam.timeseriesaggregation import TimeSeriesAggregation

data = pd.DataFrame()
idx = pd.date_range('2020-01-01 00:00:00', periods=3, freq='1H')
data['test'] = pd.Series(index=idx, data=[1, 2, 3])

tsa = TimeSeriesAggregation(data, noTypicalPeriods=3, hoursPerPeriod=1,
                            weightDict={'test': 0.1})

print(data)
print(tsa.createTypicalPeriods())
print(tsa.predictOriginalData())
print(tsa.accuracyIndicators())
```

**Comment by l-kotzur** [comment]
Thank you!
