### ISSUE TITLE
Tsam erroneously raises error after successfully solving k_medoids clustering problem with Gurobi

### ISSUE THREAD

**Issue by FlRedder** [FZJ-IEK3-VSA/tsam#54]
https://github.com/FZJ-IEK3-VSA/tsam/blob/25c5b394cc72bfc85c3b5df577675052e0f56415/tsam/utils/k_medoids_exact.py#L186-L187

The above code raises an error although Gurobi finds a valid solution for clustering method `k_medoids`. Hence, the error message should not be raised.

Possible cause for the bug:

- API changes in Pyomo (my version: 6.0.1) or Gurobi (my version: 9.1.1). The `index` attribute of `results['Solver'][0]['Termination condition']` seems not to be present in Pyomo 6.0.1 anymore. Could it be replaced by `results['Solver'][0]['Return code']`?

Hotfix:

-  If I comment out the above lines everything works just fine.

**Comment by l-kotzur** [comment]
Dear Florian, 

thanks for pointing out!
The issue should be solved with the latest release 1.1.2.

Best
Leander
