### ISSUE TITLE
Incorrect docstring of clusterOrder

### ISSUE THREAD

**Issue by mfleschutz** [FZJ-IEK3-VSA/tsam#69]
Just a friendly little hint. I saw that the docstring of the `clusterOrder` property was copied from the `clusterPeriodNoOccur` property which is incorrect.

https://github.com/FZJ-IEK3-VSA/tsam/blob/14f04dc8ab195129600ecbaa121b832dc8cbeecf/tsam/timeseriesaggregation.py#LL1117C13-L1117C13

**Comment by l-kotzur** [comment]
@maximilian-hoffmann can you fix this?

**Comment by l-kotzur** [comment]
@mfleschutz Thanks for pointing out. I corrected this in #72
