### ISSUE TITLE
Error when creating typical periods which are longer than 24h (e.g. 48h or 72h)

### ISSUE THREAD

**Issue by alicia-le** [FZJ-IEK3-VSA/tsam#70]
I am using version 2.0.1 of Pandas. Unfortunately, as of version 1.4.0, DataFrame.append() has been deprecated. So now I get an error message when I try to create typical periods longer than 24h, for example, typical periods that are 48h long.

**Comment by l-kotzur** [comment]
@rschwarz @alicia-le Sorry, I just saw this now. I updated my notification setting to respond in future earliest. 

I will release @rschwarz fix tomorrow.

**Comment by l-kotzur** [comment]
This should now be fixed with release 2.3.0. Thanks again for pointing out and fixing.
