### ISSUE TITLE
incompatible with pandas 2.0

### ISSUE THREAD

**Issue by SilkeJo** [FZJ-IEK3-VSA/tsam#74]
Since the append-method was removed from pandas 2.0, all commands using this function do not work with this pandas version.
e.g. l64 in timeseriesaggregation.py:

unstackedTimeSeries = unstackedTimeSeries.append(rep_data, ignore_index=False)

which I think should be rewritten to: 

unstackedTimeSeries=pd.concat([unstackedTimeSeries, rep_data])

**Comment by l-kotzur** [comment]
Thanks for pointing out. 

This was reported as well in issue #70 and should be solved with the latest release 2.3.0 https://pypi.org/project/tsam/

Please let me know if this solves your issue.

**Comment by SilkeJo** [comment]
yes, thanks :)
