### ISSUE TITLE
Documentation builds seem to be out of date

### ISSUE THREAD

**Issue by fneum** [FZJ-IEK3-VSA/tsam#76]
The documentation https://tsam.readthedocs.io seems to have been updated last for version 2.0.0.

**Comment by l-kotzur** [comment]
Hey Fabian,

thanks for pointing out. I updated the whole documentation and included the auto deployment .yml such that this does not happen in future. 

If things are not clear or you have further questions, feel free to reach out!

Cheers
Leander

@maximilian-hoffmann tbn
