### ISSUE TITLE
Expected incompatibility with pandas 3.0 due to changes in stack function implemetation

### ISSUE THREAD

**Issue by adbuerger** [FZJ-IEK3-VSA/tsam#81]
Dear tsam developers,

when using a recent version of pandas, I receive the following deprecation warning when using tsam:

`
The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
`

The notes referenced in the deprecation warning state that from pandas 3.0 on, the previous implementation of the stack-function will not be available anymore, cf. https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#new-implementation-of-dataframe-stack. According to their milestones, release of pandas 3.0 could be expected already around April 2024, cf. https://github.com/pandas-dev/pandas/milestone/102.

In tsam, the mentioned `stack` function is used in multiple positions in `timeseriesaggregation.py` and `durationRepresentation.py`. Since, e.g., the default sorting behavior is expected to change in the new implementation, I am unsure whether these changes in behavior could impact the outputs of tsam. Therefore, I wanted to ask whether you are already aware of this change and if it is already planned to adjust the use of pandas at these points in the code, accordingly.

Thank you for providing this very useful software!

**Comment by julian-belina** [comment]
@adbuerger Thank you for pointing out the compatability issue and sorry for the long wait. Version 2.3.3 is now compatabile with the newer pandas and numpy versions. V2.3.2 is compatible with older dependencies.
